### PR TITLE
Contributions

### PR DESCRIPTION
**Pull request by dericed**
This pull requests includes a start of a contributing guide and a license. I'm preemptively using a Creative Commons 4.0 license, but I'm now realizing that this repo may include content that is not CC such as any integrated proprietary organizational texts. Opinions on how to handle this?

### CODE REVIEW

**Comment by kgrons** [comment]
Thanks @dericed ! The Contribution Guide's Project Maintainers and Rules for contributing sections look good to me. @ekemeyer thoughts?

I agree with holding on the license/CC commit until we have a better understanding of how AMIA's organizational documents are released.

**Comment by ekemeyer** [comment]
Looks good.

Agree about holding off on CC commit.

**Comment by kgrons** [comment]
@dericed could you please re-submit a PR that only includes:
- The Contribution Guide
- subheading/text for: Project Maintainers, and rules for contributing?

**Comment by dericed** [comment]
I removed the license, though I'm still interested in finding a way to say that new contributions should be done under a certain license while the underlying material from AMIA may not be. #tbd

I removed the LICENSE file, removed reference to license in CONTRIBUTING.

In regards to adding "rules for contributing" I would normally suggest that users make a fork, then a branch, make their change, sync from upstream, then submit a pull request, but such instructions may be unwelcoming.

**Comment by dericed** [comment]
ok I added some how to data at https://github.com/amiaopensource/amia-org/pull/1/commits/4ee6e6dd3c91b532377adc073a6c1df8139670cd. Please re-review.

**Pull request merged**
